package engine

import (
	"os"
	"os/exec"
	"path/filepath"
	"testing"
	"time"

	"github.com/stretchr/testify/require"

	"github.com/odiumuniverse/beadle/pkg/skill"
)

var stubAt = time.Date(2026, 9, 16, 10, 30, 0, 0, time.UTC)

func TestStubContent(t *testing.T) {
	t.Parallel()

	dir := filepath.Join(t.TempDir(), "alpha")

	created, err := writePluginStub(dir, "alpha", "acme/tool", "1.0.0", stubAt)
	require.NoError(t, err)
	require.True(t, created)

	for _, name := range []string{skill.StubMarkerFile, farmSkillFile, stubScriptName} {
		require.FileExists(t, filepath.Join(dir, name))
	}

	key, ok := skill.IsStubDir(dir)
	require.True(t, ok)
	require.Equal(t, "acme/tool", key)

	doc, err := os.ReadFile(filepath.Join(dir, farmSkillFile)) //nolint:gosec // G304: the test reads its own temp file
	require.NoError(t, err)
	require.Contains(t, string(doc), `name: "alpha"`)
	require.Contains(t, string(doc), "description: unavailable plugin stub")
	require.Contains(t, string(doc), "acme/tool@1.0.0")
	require.Contains(t, string(doc), "2026-09-16T10:30:00Z")

	info, err := os.Stat(filepath.Join(dir, stubScriptName))
	require.NoError(t, err)
	require.Equal(t, os.FileMode(0o755), info.Mode().Perm())

	before := snapshotDir(t, dir)

	created, err = writePluginStub(dir, "alpha", "acme/tool", "1.0.0", stubAt)
	require.NoError(t, err)
	require.False(t, created)
	require.Equal(t, before, snapshotDir(t, dir), "repeated generation must be byte-stable")
}

func TestStubScriptFailsLoudly(t *testing.T) {
	t.Parallel()

	dir := filepath.Join(t.TempDir(), "alpha")

	_, err := writePluginStub(dir, "alpha", "acme/tool", "1.0.0", stubAt)
	require.NoError(t, err)

	out, err := exec.CommandContext(t.Context(), "sh", filepath.Join(dir, stubScriptName)).Output() //nolint:gosec // G204: the script is generated by this test

	var exit *exec.ExitError
	require.ErrorAs(t, err, &exit)
	require.Equal(t, 1, exit.ExitCode())
	require.Contains(t, string(out), "acme/tool@1.0.0, which is no longer installed")
	require.Contains(t, string(out), "beadle heal")
}

func TestStubRefusesForeign(t *testing.T) {
	t.Parallel()

	dir := filepath.Join(t.TempDir(), "alpha")
	require.NoError(t, os.MkdirAll(dir, 0o750))
	require.NoError(t, os.WriteFile(filepath.Join(dir, farmSkillFile), []byte("# real\n"), 0o600))

	created, err := writePluginStub(dir, "alpha", "acme/tool", "1.0.0", stubAt)
	require.NoError(t, err)
	require.False(t, created)

	data, err := os.ReadFile(filepath.Join(dir, farmSkillFile)) //nolint:gosec // G304: the test reads its own temp file
	require.NoError(t, err)
	require.Equal(t, "# real\n", string(data))
	require.NoFileExists(t, filepath.Join(dir, skill.StubMarkerFile))
}

func TestStubRefusesUnsafeInput(t *testing.T) {
	t.Parallel()

	cases := []struct {
		desc    string
		name    string
		key     string
		version string
	}{
		{desc: "dollar in version", name: "alpha", key: "acme/tool", version: "1.0.$0"},
		{desc: "backtick in name", name: "al`pha", key: "acme/tool", version: "1.0.0"},
		{desc: "quote in name", name: "al'pha", key: "acme/tool", version: "1.0.0"},
		{desc: "double quote in name", name: `al"pha`, key: "acme/tool", version: "1.0.0"},
		{desc: "backslash in name", name: `al\pha`, key: "acme/tool", version: "1.0.0"},
		{desc: "whitespace in name", name: "al pha", key: "acme/tool", version: "1.0.0"},
		{desc: "escaping in name", name: "../alpha", key: "acme/tool", version: "1.0.0"},
		{desc: "whitespace in key", name: "alpha", key: "acme /tool", version: "1.0.0"},
	}

	for _, tc := range cases {
		t.Run(tc.desc, func(t *testing.T) {
			t.Parallel()

			dir := filepath.Join(t.TempDir(), "skill")

			created, err := writePluginStub(dir, tc.name, tc.key, tc.version, stubAt)
			require.ErrorIs(t, err, errUnsafeStubInput)
			require.False(t, created)
			require.NoDirExists(t, dir)
		})
	}
}

func snapshotDir(t *testing.T, dir string) map[string]string {
	t.Helper()

	data := map[string]string{}

	entries, err := os.ReadDir(dir)
	require.NoError(t, err)

	for _, entry := range entries {
		content, err := os.ReadFile(filepath.Join(dir, entry.Name())) //nolint:gosec // G304: the test reads its own temp file
		require.NoError(t, err)

		data[entry.Name()] = string(content)
	}

	return data
}
