package engine

import (
	"errors"
	"io/fs"
	"os"
	"os/exec"
	"path/filepath"
	"testing"
	"time"

	. "github.com/smartystreets/goconvey/convey"

	"github.com/odiumuniverse/beadle/pkg/skill"
)

var stubAt = time.Date(2026, 9, 16, 10, 30, 0, 0, time.UTC)

func snapshotDir(t *testing.T, dir string) map[string]string {
	t.Helper()

	data := map[string]string{}

	entries, err := os.ReadDir(dir)
	if err != nil {
		t.Fatalf("readdir %s: %v", dir, err)
	}

	for _, entry := range entries {
		content, err := os.ReadFile(filepath.Join(dir, entry.Name())) //nolint:gosec // G304: the test reads its own temp file
		if err != nil {
			t.Fatalf("read %s: %v", entry.Name(), err)
		}

		data[entry.Name()] = string(content)
	}

	return data
}

func TestStubContent(t *testing.T) {
	Convey("Given a plugin stub written to a fresh directory", t, func() {
		dir := filepath.Join(t.TempDir(), "alpha")

		created, err := writePluginStub(dir, "alpha", "acme/tool", "1.0.0", stubAt)
		So(err, ShouldBeNil)

		Convey("When it is read back and regenerated", func() {
			key, ok := skill.IsStubDir(dir)

			doc, readErr := os.ReadFile(filepath.Join(dir, farmSkillFile)) //nolint:gosec // G304: the test reads its own temp file
			So(readErr, ShouldBeNil)

			info, statErr := os.Stat(filepath.Join(dir, stubScriptName))
			So(statErr, ShouldBeNil)

			before := snapshotDir(t, dir)

			createdAgain, err := writePluginStub(dir, "alpha", "acme/tool", "1.0.0", stubAt)
			So(err, ShouldBeNil)

			Convey("Then the stub is well-formed and byte-stable", func() {
				So(created, ShouldBeTrue)

				for _, name := range []string{skill.StubMarkerFile, farmSkillFile, stubScriptName} {
					_, existsErr := os.Stat(filepath.Join(dir, name))
					So(existsErr, ShouldBeNil)
				}

				So(ok, ShouldBeTrue)
				So(key, ShouldEqual, "acme/tool")

				So(string(doc), ShouldContainSubstring, `name: "alpha"`)
				So(string(doc), ShouldContainSubstring, "description: unavailable plugin stub")
				So(string(doc), ShouldContainSubstring, "acme/tool@1.0.0")
				So(string(doc), ShouldContainSubstring, "2026-09-16T10:30:00Z")

				So(info.Mode().Perm(), ShouldEqual, os.FileMode(0o755))

				So(createdAgain, ShouldBeFalse)
				So(snapshotDir(t, dir), ShouldResemble, before)
			})
		})
	})
}

func TestStubScriptFailsLoudly(t *testing.T) {
	Convey("Given a generated stub script", t, func() {
		dir := filepath.Join(t.TempDir(), "alpha")

		_, err := writePluginStub(dir, "alpha", "acme/tool", "1.0.0", stubAt)
		So(err, ShouldBeNil)

		Convey("When it is executed", func() {
			out, execErr := exec.CommandContext(t.Context(), "sh", filepath.Join(dir, stubScriptName)).Output() //nolint:gosec // G204: the script is generated by this test

			var exitCmd *exec.ExitError
			So(errors.As(execErr, &exitCmd), ShouldBeTrue)

			Convey("Then it fails loudly and points at heal", func() {
				So(exitCmd.ExitCode(), ShouldEqual, 1)
				So(string(out), ShouldContainSubstring, "acme/tool@1.0.0, which is no longer installed")
				So(string(out), ShouldContainSubstring, "beadle heal")
			})
		})
	})
}

func TestStubRefusesForeign(t *testing.T) {
	Convey("Given a directory holding a real skill file", t, func() {
		dir := filepath.Join(t.TempDir(), "alpha")
		So(os.MkdirAll(dir, 0o750), ShouldBeNil)
		So(os.WriteFile(filepath.Join(dir, farmSkillFile), []byte("# real\n"), 0o600), ShouldBeNil)

		Convey("When a stub is written", func() {
			created, err := writePluginStub(dir, "alpha", "acme/tool", "1.0.0", stubAt)

			data, readErr := os.ReadFile(filepath.Join(dir, farmSkillFile)) //nolint:gosec // G304: the test reads its own temp file
			_, markerErr := os.Stat(filepath.Join(dir, skill.StubMarkerFile))

			Convey("Then it refuses and leaves the real skill alone", func() {
				So(err, ShouldBeNil)
				So(created, ShouldBeFalse)

				So(readErr, ShouldBeNil)
				So(string(data), ShouldEqual, "# real\n")
				So(errors.Is(markerErr, fs.ErrNotExist), ShouldBeTrue)
			})
		})
	})
}

func TestStubRefusesUnsafeInput(t *testing.T) {
	Convey("Given a table of unsafe stub inputs", t, func() {
		cases := []struct {
			desc    string
			name    string
			key     string
			version string
		}{
			{desc: "dollar in version", name: "alpha", key: "acme/tool", version: "1.0.$0"},
			{desc: "backtick in name", name: "al`pha", key: "acme/tool", version: "1.0.0"},
			{desc: "quote in name", name: "al'pha", key: "acme/tool", version: "1.0.0"},
			{desc: "double quote in name", name: `al"pha`, key: "acme/tool", version: "1.0.0"},
			{desc: "backslash in name", name: `al\pha`, key: "acme/tool", version: "1.0.0"},
			{desc: "whitespace in name", name: "al pha", key: "acme/tool", version: "1.0.0"},
			{desc: "escaping in name", name: "../alpha", key: "acme/tool", version: "1.0.0"},
			{desc: "whitespace in key", name: "alpha", key: "acme /tool", version: "1.0.0"},
		}

		for _, tc := range cases {
			Convey("When the "+tc.desc+" is used", func() {
				dir := filepath.Join(t.TempDir(), "skill")

				created, err := writePluginStub(dir, tc.name, tc.key, tc.version, stubAt)

				_, dirErr := os.Stat(dir)

				Convey("Then it is rejected and no directory is created", func() {
					So(errors.Is(err, errUnsafeStubInput), ShouldBeTrue)
					So(created, ShouldBeFalse)
					So(errors.Is(dirErr, fs.ErrNotExist), ShouldBeTrue)
				})
			})
		}
	})
}
